config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
  	member do # memberメゾットを使うとユーザーidが含まれているURLを扱うようになる。
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  root 'home#top'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :post_books do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :post_book

	validates :comment, presence: true #空欄
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post_book

	#ひとりが１つの投稿に対して１つしかいいねを付けられないようにする
	validates_uniqueness_of :post_book_id, scope: :user_id
end

app/models/post_book.rb
class PostBook < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user) #各投稿(book)に自分(current_user)のいいね(favorite)がついているか判断する
            favorites.where(user_id: user.id).exists? # exists = 存在
    end
	validates :title, presence: true, length: {maximum: 30}
	validates :body, presence: true, length: {maximum: 200}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User" #なぜ_idは要らないのか？
  belongs_to :followed, class_name: "User" #なぜ_idは要らないのか？

  #念のためバリデーション。なくても普通の動作は可能で大きな問題はない。
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(other_user)
    follower.create(followed_id: other_user)
  end

  # ユーザーのフォローを外す
  def unfollow(other_user)
    follower.find_by(followed_id: other_user).destroy
  end

  # フォローしていればtrueを返す
  def following?(other_user)
    following_user.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
  	user_path(@user.id)
  end

  def after_sign_out_path_for(resource)
  	root_path
  end

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		@post_book = PostBook.find(params[:post_book_id])
		@book_comment = current_user.book_comments.new(book_comment_params)
		@book_comment.post_book_id = @post_book.id
		@book_comment.user_id = current_user.id
		if @book_comment.save
			redirect_back(fallback_location: root_path)
		else
			@my_book = @post_book
			@user = @post_book.user
			render 'post_books/show'
		end
	end

	def destroy
		@book_comment = BookComment.find(params[:post_book_id])
		@book_comment.destroy
		redirect_back(fallback_location: root_path)
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@post_book = PostBook.find(params[:post_book_id])
		@favorite = current_user.favorites.new(post_book_id: params[:post_book_id])
		@favorite.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		@post_book = PostBook.find(params[:post_book_id])
		@favorite = current_user.favorites.find_by(post_book_id: @post_book.id)
		@favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def top
  end
end

app/controllers/post_books_controller.rb
class PostBooksController < ApplicationController
  before_action :authenticate_user!
  before_action :current_book, only:[:edit, :update]

  def create
    @post_book = PostBook.new(post_book_params)
    @post_book.user_id = current_user.id
    if @post_book.save
       redirect_to post_book_path(@post_book.id), notice: "You have creatad book successfully."
    else
      @post_books = PostBook.all
      @user = User.find(current_user.id)
      render "index"
    end
  end

  def index
    @post_book = PostBook.new
    @post_books = PostBook.all
    @user = User.find(current_user.id)
  end

  def show
    @my_book = PostBook.find(params[:id])
    @post_book = PostBook.new
    @user = @my_book.user
    @book_comment = BookComment.new
  end

  def edit
    @post_book = PostBook.find(params[:id])
  end

  def update
    @post_book = PostBook.find(params[:id])
    if @post_book.update(post_book_params)
       redirect_to post_book_path(@post_book), notice: "You have updated book successfully."
    else
       render "edit"
    end
  end

  def destroy
  	@post_book = PostBook.find(params[:id])
    @post_book.destroy
    redirect_to post_books_path
  end

  private

  def current_book
    @post_book = PostBook.find(params[:id])
    if @post_book.user != current_user
       redirect_to post_book_path
    end
  end

  def post_book_params
    params.require(:post_book).permit(:title, :body, :user_id)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		current_user.follow(params[:other_user])
		redirect_back(fallback_location: root_path)
	end

	def destroy
		current_user.unfollow(params[:other_user])
		redirect_back(fallback_location: root_path)
	end

	def follower
	    user = User.find(params[:other_user])
	    @users = user.following_user
	end

	def followed
		user = User.find(params[:other_user])
	    @users = user.follower_user
	end

	private
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :b_user, only:[:edit, :update]
  def top
  end

  def index
    @user = User.find(current_user.id)
    @users = User.all
    @post_book = PostBook.new
  end

  def show
    @user = User.find(params[:id])
    @post_book = PostBook.new
    @post_books = @user.post_books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def b_user
    @user = User.find(params[:id])
    if @user != current_user
       redirect_to user_path(current_user)
    end
  end

  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_books_helper.rb
module PostBooksHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<main>
	<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers2!</h1>

</main>

app/views/home/top.html.erb
	<p><%= flash[:notice] %></p>

	<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers2 !!</h1>
	<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><span>Bookers,</span><br>

	you can share and exchange your opinions , inpressions , and emotions<br>

	about various books!</p>


	<p><%= link_to "Log in", new_user_session_path %><br>
	<%= link_to "Sign Up", new_user_registration_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-contents">
        <h2 class="header-title">Bookers2</h2>
        <nav>
          <ul class="nav-list">
            <% if user_signed_in? %>
              <li class="nav-list-item">
                <%= link_to user_path(current_user.id) do %>
                  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                  Home
                <% end %>
              </li>
              <li class="nav-list-item">
                <%= link_to users_path do %>
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                  Users
                <% end %>
              </li>
              <li class="nav-list-item">
                <%= link_to post_books_path do %>
                  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
                  Books
                <% end %>
              </li>
              <li class="nav-list-item">
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                  logout
                <% end %>
              </li>
            <% else %>
              <li class="nav-list-item">
                <%= link_to root_path do %>
                  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                  Home
                <% end %>
              </li>
              <li class="nav-list-item">
                <%= link_to home_about_path do %>
                  <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
                  About
                <% end %>
              </li>
              <li class="nav-list-item">
                <%= link_to new_user_registration_path do %>
                sign up
                <% end %>
              </li>
              <li class="nav-list-item">
                <%= link_to user_session_path do %>
                  <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                  login
                <% end %>
              </li>
            <% end %>
          </ul>
      </nav>
    </div>
    </header>

    <%= yield %>

    <footer>
        CopyRight Infratop.inc
    </footer>
  </body>
</html>

app/views/post_books/edit.html.erb
<main>
	<h1>Editing Book</h1>

	<% if @post_book.errors.any? %>
		<%= @post_book.errors.count %>error prohibited this post_book from being saved:<br>
			<ul>
			<% @post_book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
	<% end %>

	<%= form_for(@post_book, url:"/post_books/#{@post_book.id}") do |f| %>
		<p>Title<br>
		<%= f.text_field :title %></p>

		<p>Opinion<br>
		<%= f.text_area :body %></p>

		<%= f.submit 'Update Book' %>

	<% end %>

	<p><%= link_to "Show", post_book_path(@post_book) %> |
	<%= link_to "Back", post_books_path %></p>
</main>

app/views/post_books/index.html.erb
<div class="container">
	<div class="row">
		<%= render 'users/side', user: @user, post_book: @post_book %>

		<div class="col-xs-9">
			<table width="800">
				<h1>Books</h1>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
				</tr>
				<% @post_books.each do |post_book| %>
					<tr align="left">
						<td><%= link_to user_path(post_book.user.id) do %>
							<%= attachment_image_tag post_book.user, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td><%= link_to post_book.title, post_book_path(post_book) %></td>
						<td><%= post_book.body %></td>
						<td>
							<% if post_book.favorited_by?(current_user) %>
							    <%= link_to post_book_favorites_path(post_book), method: :delete do %>
							    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							    <%= post_book.favorites.count %>
							    <% end %>
							<% else %>
							    <%= link_to post_book_favorites_path(post_book), method: :post do %>
							    <i class="fa fa-heart-o" aria-hidden="true"></i>
							    <%= post_book.favorites.count %>
							    <% end %>
							<% end %>
						</td>
						<td>コメント:<%= post_book.book_comments.count %></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/post_books/show.html.erb
<div class="container">
	<div class="row">
		<p><%= flash[:notice] %></p>

		<%= render 'users/side', user: @user, post_book: @post_book %>

		<div class="col-xs-9">
			<table width="800">
				<h1>Book detail</h1>
				<tr>
					<td>
						<%= link_to user_path(@user.id) do %>
							<%= attachment_image_tag @user, :profile_image, size: "60x60", fallback: "no_image.jpg" %><br>
							<%= @user.name%>
						<% end %>
					</td>
					<td><%= link_to @my_book.title, post_book_path(@my_book)%></td>
					<td><%= @my_book.body %></td>
					<td>
						<% if @my_book.favorited_by?(current_user) %>
						    <%= link_to post_book_favorites_path(@my_book), method: :delete do %>
						    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
						    <%= @my_book.favorites.count %>
						    <% end %>
						<% else %>
						    <%= link_to post_book_favorites_path(@my_book), method: :post do %>
						    <i class="fa fa-heart-o" aria-hidden="true"></i>
						    <%= @my_book.favorites.count %>
						    <% end %>
						<% end %>
					</td>
					<td>コメント:<%= @my_book.book_comments.count %></td>
					<% if @my_book.user == current_user %>
						<td class="edit-btn"><%= link_to "Edit", edit_post_book_path(@my_book.id), class: "pull-right" %></td>
					<% end %>
					<% if @my_book.user == current_user %>
						<td><%= link_to "Destroy", post_book_path(@my_book.id), method: :delete, "data-confirm" => "本当に削しますか？" %></td>
					<% end %>
				</tr>

				<% if @book_comment.errors.any? %>
					<%= @book_comment.errors.count %>error prohibited this book_comment from being saved:<br>
						<ul>
						<% @book_comment.errors.full_messages.each do |message| %>
							<li><%= message %></li>
						<% end %>
						</ul>
				<% end %>
				<% @my_book.book_comments.each do |book_comment| %>
					<tr>
						<td>
							<%= link_to user_path(book_comment.user) do %>
								<%= attachment_image_tag book_comment.user, :profile_image, size: "60x60", fallback: "no_image.jpg" %><br>
								<%= book_comment.user.name %>
							<% end %>
							<%= book_comment.comment %>
							<% if book_comment.user == current_user %>
								<%= link_to "Destroy", post_book_book_comments_path(book_comment), class: "book-destroy book-btn", method: :delete, "data-confirm" => "本当に削しますか？" %>
							<% end %>
						</td>
					</tr>
				<% end %>
			</table>
			<%= form_for [@my_book, @book_comment] do |f| %>
            	<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
			    <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/_side.html.erb
<div class="col-xs-3">
	<h1>User info</h1>

	<table width="350">
		<tr><%= attachment_image_tag user, :profile_image, size: "150x150", fallback: "no_image.jpg"%></tr>
		<tr>
			<th>name:</th>
			<th><%= user.name %></th>
		</tr>
		<tr>
			<th>introduction:</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
		    <th>follows</th>
		    <th><%= link_to user.follower.count, following_user_path(user) %></th>
		</tr>
		<tr>
		    <th>followers</th>
		    <th><%= link_to user.followed.count, followers_user_path(user) %></th>
  		</tr>
	</table>
	<!-- フォローボタン -->
	<% if current_user != user %>
		<% if current_user.following?(user) %>
			<%= link_to 'フォロー外す', relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
		<% else %>
	    	<%= link_to 'フォローする', relationships_path(user.id), method: :POST, class: "btn btn-success" %>
		<% end %>
	<% end %>

	<% if user.id == current_user.id %>
		<%= link_to edit_user_path(user.id) do %>
			<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
		<% end %>
	<% end %>

	<% if @post_book.errors.any? %>
		<%= @post_book.errors.count %>error prohibited this post_book from being saved:<br>
			<ul>
			<% @post_book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
	<% end %>

	<h1>New Book</h1>
	<%= form_for(post_book) do |f| %>
		<div class="new-book-form">
			<p>Title</p>
			<%= f.text_field :title %>

			<p>Opinion</p>
			<%= f.text_area :body %>

			<p><%= f.submit 'Create Book' %></p>
		</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<main>
	<h1>User info</h1>

	<% if @user.errors.any? %>
		<%= @user.errors.count %>error prohibited this user from being saved:<br>
			<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
	<% end %>

	<%= form_for(@user) do |f| %>
		<p>Name
		<%= f.text_field :name %></p>

		<p>Image</p>
		<%= f.attachment_field :profile_image %>

		<p>Introduction
		<%= f.text_area :introduction %></p>

		<p><%= f.submit 'Update User' %></p>

	<% end %>
</main>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<%= render 'users/side', user: @user, post_book: @post_book %>

		<div class="col-xs-9">
			<table width="800">
				<h1>Users</h1>
				<tr>
					<th>image</th>
					<th>name</th>
				</tr>
				<% @users.each do |user| %>
					<tr align="left">
						<td><%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpg"%></td>
						<td><%= user.name %></td>
						<td><%= link_to "Show", user_path(user) %></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<p><%= flash[:notice] %></p>

		<%= render 'users/side', user: @user, post_book: @post_book %>

		<div class="col-xs-9">
			<table width= "800">
				<h1>Books</h1>
				<tr align="left">
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
				</tr>
				<% @post_books.each do |post_book| %>
					<tr>
						<td><%= link_to user_path(post_book.user.id) do %>
								<%= attachment_image_tag post_book.user, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td><%= link_to post_book.title, post_book_path(post_book) %></td>
						<td><%= post_book.body %></td>
						<td>コメント:<%= post_book.book_comments.count %></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/top.html.erb
<main>
	<p><%= flash[:notice] %></p>

	<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers2 !!</h1>
	<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><span>Bookers,</span><br>

	you can share and exchange your opinions , inpressions , and emotions<br>

	about various books!</p>


	<p><%= link_to "Log in", new_user_session_path %><br>
	<%= link_to "Sign Up", new_user_registration_path %></p>
</main>